### ISSUE TITLE
Parse all info from site

### ISSUE THREAD

**Issue by ya6lis** [vrokyta/arthroscopy-content#3]
## Tasks description

Parse all data from all pages of the site. Md files shoud be configured like "About" and "Privacy"

## Tasks

- [x] Parse all data from "[Головна](https://arthroscopy.lviv.ua/)"
- [x] Parse all data from "[Про лікаря](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=55&Itemid=303&lang=ua)"
    - [x] Parse all data from "[Сертифікати та дипломи](https://arthroscopy.lviv.ua/index.php?option=com_phocagallery&view=category&id=2&Itemid=304&lang=ua)"
    - [x] Parse all data from "[Фотографії](https://arthroscopy.lviv.ua/index.php?option=com_phocagallery&view=category&id=1&Itemid=305&lang=ua)"
- [x] Parse all data from "[Контакти](https://arthroscopy.lviv.ua/index.php?option=com_contact&view=contact&id=2&Itemid=310&lang=ua)"
    - [x] Parse all data from "[Не додзвонились](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=61&Itemid=311&lang=ua)"
    - [x] Parse all data from "[Корисна інформація](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=62&Itemid=312&lang=ua)"
    - [x] Parse all data from "[Запис на прийом](https://arthroscopy.lviv.ua/index.php?option=com_mad4joomla&view=form&jid=1&Itemid=499&lang=ua)"
- [x] Parse all data from "[Колінний суглоб](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=11&Itemid=313&lang=ua)"
    - [x] Parse all data from "[Анатомія колінного суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=12&Itemid=314&lang=ua)"
    - [x] Parse all data from "[Симптоми, діагностика, лікування](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=128&Itemid=315&lang=ua)"
    - [x] Parse all data from "[Меніски](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=14&Itemid=316&lang=ua)"
    - [x] Parse all data from "[Хрестоподібні зв'язки](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=15&Itemid=317&lang=ua)"
    - [x] Parse all data from "[Травми колінного суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=16&Itemid=318&lang=ua)"
    - [x] Parse all data from "[Травма меніска](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=17&Itemid=319&lang=ua)"
    - [x] Parse all data from "[Розрив хрестоподібної зв'язки](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=18&Itemid=320&lang=ua)"
    - [x] Parse all data from "[Хвороби колінного суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=19&Itemid=321&lang=ua)"
    - [x] Parse all data from "[Артроз, остеоартроз, гонартроз](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=20&Itemid=322&lang=ua)"
    - [x] Parse all data from "[Хвороба Кеніга](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=21&Itemid=323&lang=ua)"
    - [x] Parse all data from "[Кіста Беккера](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=22&Itemid=324&lang=ua)"
    - [x] Parse all data from "[Артроскопія колінного суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=65&Itemid=325&lang=ua)"
    - [x] Parse all data from "[Ендопротезування колінного суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=66&Itemid=326&lang=ua)"
