### ISSUE TITLE
Parse all info from site (part #2)

### ISSUE THREAD

**Issue by ya6lis** [vrokyta/arthroscopy-content#4]
## Tasks description

Parse all data from all pages of the site. Md files shoud be configured like "About" and "Privacy"

## Tasks

- [x] Parse all data from "[Плечовий та ліктьовий суглоби](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=24&Itemid=328&lang=ua)"
    - [x] Parse all data from "[Анатомія](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=25&Itemid=329&lang=ua)"
    - [x] Parse all data from "[Симптоми, діагностика, лікування](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=26&Itemid=330&lang=ua)"
    - [x] Parse all data from "[Травми плечового та ліктьового суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=68&Itemid=331&lang=ua)"
    - [x] Parse all data from "[Вивих плеча](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=28&Itemid=332&lang=ua)"
    - [x] Parse all data from "[Хвороби плечового та ліктьового суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=27&Itemid=333&lang=ua)"
    - [x] Parse all data from "[Артроскопія плечового та ліктьового суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=29&Itemid=334&lang=ua)"
- [x] Parse all data from "[Кульшовий суглоб](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=31&Itemid=336&lang=ua)"
    - [x] Parse all data from "[Анатомія](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=32&Itemid=337&lang=ua)"
    - [x] Parse all data from "[Симптоми, діагностика, лікування](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=33&Itemid=338&lang=ua)"
    - [x] Parse all data from "[Травми кульшового суглобу](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=34&Itemid=339&lang=ua)"
    - [x] Parse all data from "[Переломи шийки стегна і вертлюговоїобласті](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=35&Itemid=340&lang=ua)"
    - [x] Parse all data from "[Хвороби кульшового суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=36&Itemid=341&lang=ua)"
    - [x] Parse all data from "[Артроскопія кульшового суглобу](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=37&Itemid=342&lang=ua)"
    - [x] Parse all data from "[Ендопротезування кульшового суглоба](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=38&Itemid=343&lang=ua)"
- [x] Parse all data from "[Гомілковостоп](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=40&Itemid=345&lang=ua)"
    - [x] Parse all data from "[Анатомія](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=41&Itemid=346&lang=ua)"
    - [x] Parse all data from "[Симптоми, діагностика, лікування](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=42&Itemid=347&lang=ua)"
    - [x] Parse all data from "[Травми гомілковостопного суглобу](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=43&Itemid=348&lang=ua)"
    - [x] Parse all data from "[Хвороби гомілковостопного суглобу](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=44&Itemid=349&lang=ua)"
    - [x] Parse all data from "[Вальгусна деформація 1 пальця стопи](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=45&Itemid=350&lang=ua)"
    - [x] Parse all data from "[Артроскопія гомілковостопа](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=46&Itemid=351&lang=ua)"
- [x] Parse all data from "[Артроскопія](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=48&Itemid=353&lang=ua)"
    - [x] Parse all data from "[Опис](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=49&Itemid=354&lang=ua)"
    - [x] Parse all data from "[Вартість](https://arthroscopy.lviv.ua/index.php?option=com_content&view=category&layout=blog&id=50&Itemid=355&lang=ua)"
